import { defineItems, type ItemDef } from './defs';
import { T } from './tuning';

const D = T.DAY;

const resources: ItemDef[] = [
  { id: 'twigs', name: 'Twigs', stack: 40, fuel: 30, cook: { inedible: 1 }, desc: 'Brittle, but useful.' },
  { id: 'cutgrass', name: 'Cut Grass', stack: 40, fuel: 30, desc: 'Dry and fibrous.' },
  { id: 'log', name: 'Log', stack: 20, fuel: 90, desc: 'A good, honest log.' },
  { id: 'rocks', name: 'Rocks', stack: 40, desc: 'Solid and dependable.' },
  { id: 'flint', name: 'Flint', stack: 40, desc: 'Sharp enough to cut the dark.' },
  { id: 'gold', name: 'Gold Nugget', stack: 40, desc: 'Shiny. Useless to eat.' },
  { id: 'pinecone', name: 'Pine Cone', stack: 40, fuel: 30, deploy: 'pine_sapling', desc: 'A tree waiting to happen.' },
  { id: 'cutreeds', name: 'Cut Reeds', stack: 40, fuel: 30, desc: 'Hollow, like the land.' },
  { id: 'petals', name: 'Petals', stack: 40, fuel: 15, perish: 6 * D, food: { health: 1, hunger: 0, sanity: 0, type: 'veggie' }, desc: 'They smell like better days.' },
  { id: 'charcoal', name: 'Charcoal', stack: 40, fuel: 90, desc: 'What remains of the wood.' },
  { id: 'ash', name: 'Ash', stack: 40, desc: 'Fire has been here.' },
  { id: 'rope', name: 'Rope', stack: 40, fuel: 90, desc: 'Twisted grass. Holds things together.' },
  { id: 'boards', name: 'Boards', stack: 40, fuel: 360, desc: 'Flat and square. Civilized.' },
  { id: 'cutstone', name: 'Cut Stone', stack: 40, desc: 'The start of something permanent.' },
  { id: 'silk', name: 'Silk', stack: 40, desc: 'Sticky, strong, and spidery.' },
  { id: 'spidergland', name: 'Spider Gland', stack: 40, heal: 8, desc: 'Squishy. Good for wounds, oddly.' },
  { id: 'houndstooth', name: "Hound's Tooth", stack: 40, desc: 'It bit me first.' },
  { id: 'hogskin', name: 'Hog Hide', stack: 20, desc: 'Tough and a bit bristly.' },
  { id: 'wool', name: 'Shag Wool', stack: 40, fuel: 90, desc: 'Thick and warm. Smells like beast.' },
  { id: 'manure', name: 'Manure', stack: 20, fuel: 90, tags: ['fertilizer'], desc: 'The circle of life.' },
  { id: 'rot', name: 'Rot', stack: 40, fuel: 30, tags: ['fertilizer'], desc: 'It was food once.' },
  { id: 'nightmarefuel', name: 'Dread Essence', stack: 40, fuel: 90, desc: 'It squirms when I look away.' },
  { id: 'frostheart', name: 'Frost Heart', stack: 1, tags: ['coolant'], desc: 'Still cold. Still beating, a little.' },
  { id: 'rabbit', name: 'Rabbit', stack: 5, desc: 'Cute. Wriggly. Dinner?' },
];

const meatLike = (
  id: string,
  name: string,
  raw: [number, number, number],
  cookedName: string,
  cooked: [number, number, number],
  cookedPerish: number,
  tags: ItemDef['cook'],
  dried?: string,
  dryDays?: number,
  type: 'meat' | 'monster' = 'meat',
): ItemDef[] => [
  {
    id,
    name,
    stack: 20,
    perish: 6 * D,
    food: { health: raw[0], hunger: raw[1], sanity: raw[2], type },
    cooked: `${id}_cooked`,
    dried,
    dryDays,
    cook: tags,
    hogTreat: true,
  },
  {
    id: `${id}_cooked`,
    name: cookedName,
    stack: 20,
    perish: cookedPerish * D,
    food: { health: cooked[0], hunger: cooked[1], sanity: cooked[2], type },
    cook: tags,
    hogTreat: true,
  },
];

const foods: ItemDef[] = [
  ...meatLike('meat', 'Meat', [1, 25, -10], 'Cooked Meat', [3, 25, 0], 10, { meat: 1 }, 'jerky', 2),
  ...meatLike('morsel', 'Morsel', [0, 12.5, -10], 'Cooked Morsel', [1, 12.5, 0], 10, { meat: 0.5 }, 'smalljerky', 1),
  ...meatLike('froglegs', 'Frog Legs', [0, 12.5, -10], 'Cooked Frog Legs', [1, 12.5, 0], 10, { meat: 0.5 }, 'smalljerky', 1),
  ...meatLike('monstermeat', 'Monster Meat', [-20, 18.75, -15], 'Cooked Monster Meat', [-3, 18.75, -10], 15, { meat: 1, monster: 1 }, 'monsterjerky', 1, 'monster'),
  { id: 'jerky', name: 'Jerky', stack: 20, perish: 20 * D, food: { health: 20, hunger: 25, sanity: 15, type: 'meat' }, cook: { meat: 1 }, hogTreat: true },
  { id: 'smalljerky', name: 'Small Jerky', stack: 20, perish: 20 * D, food: { health: 8, hunger: 12.5, sanity: 10, type: 'meat' }, cook: { meat: 0.5 }, hogTreat: true },
  { id: 'monsterjerky', name: 'Monster Jerky', stack: 20, perish: 20 * D, food: { health: -3, hunger: 18.75, sanity: -5, type: 'monster' }, cook: { meat: 1, monster: 1 } },

  { id: 'berries', name: 'Berries', stack: 40, perish: 6 * D, food: { health: 0, hunger: 9.375, sanity: 0, type: 'veggie' }, cooked: 'berries_cooked', cook: { fruit: 0.5 }, deploy: undefined },
  { id: 'berries_cooked', name: 'Roasted Berries', stack: 40, perish: 3 * D, food: { health: 1, hunger: 12.5, sanity: 0, type: 'veggie' }, cook: { fruit: 0.5 } },
  { id: 'carrot', name: 'Carrot', stack: 40, perish: 10 * D, food: { health: 1, hunger: 12.5, sanity: 0, type: 'veggie' }, cooked: 'carrot_cooked', cook: { veggie: 1 } },
  { id: 'carrot_cooked', name: 'Roasted Carrot', stack: 40, perish: 6 * D, food: { health: 3, hunger: 12.5, sanity: 0, type: 'veggie' }, cook: { veggie: 1 } },
  { id: 'corn', name: 'Corn', stack: 40, perish: 10 * D, food: { health: 3, hunger: 25, sanity: 0, type: 'veggie' }, cooked: 'corn_cooked', cook: { veggie: 1 } },
  { id: 'corn_cooked', name: 'Popcorn', stack: 40, perish: 15 * D, food: { health: 3, hunger: 12.5, sanity: 0, type: 'veggie' }, cook: { veggie: 1 } },
  { id: 'pumpkin', name: 'Pumpkin', stack: 20, perish: 10 * D, food: { health: 3, hunger: 37.5, sanity: 0, type: 'veggie' }, cooked: 'pumpkin_cooked', cook: { veggie: 1 } },
  { id: 'pumpkin_cooked', name: 'Hot Pumpkin', stack: 20, perish: 6 * D, food: { health: 8, hunger: 37.5, sanity: 0, type: 'veggie' }, cook: { veggie: 1 } },
  { id: 'eggplant', name: 'Eggplant', stack: 20, perish: 10 * D, food: { health: 8, hunger: 25, sanity: 0, type: 'veggie' }, cooked: 'eggplant_cooked', cook: { veggie: 1 } },
  { id: 'eggplant_cooked', name: 'Braised Eggplant', stack: 20, perish: 6 * D, food: { health: 20, hunger: 25, sanity: 0, type: 'veggie' }, cook: { veggie: 1 } },
  { id: 'watermelon', name: 'Watermelon', stack: 20, perish: 6 * D, food: { health: 3, hunger: 12.5, sanity: 5, type: 'veggie', temp: -30, tempTime: 5 }, cooked: 'watermelon_cooked', cook: { fruit: 1 } },
  { id: 'watermelon_cooked', name: 'Grilled Watermelon', stack: 20, perish: 3 * D, food: { health: 1, hunger: 12.5, sanity: -1.5, type: 'veggie' }, cook: { fruit: 1 } },
  { id: 'seeds', name: 'Seeds', stack: 40, perish: 40 * D, food: { health: 0, hunger: 4.6875, sanity: 0, type: 'seeds' }, cooked: 'seeds_cooked', tags: ['seed'] },
  { id: 'seeds_cooked', name: 'Toasted Seeds', stack: 40, perish: 10 * D, food: { health: 1, hunger: 4.6875, sanity: 0, type: 'seeds' } },

  // Cook Pot dishes (health / hunger / sanity from KB 04)
  { id: 'meatballs', name: 'Meatballs', stack: 40, perish: 10 * D, food: { health: 3, hunger: 62.5, sanity: 5, type: 'meat' }, hogTreat: true },
  { id: 'meatystew', name: 'Meaty Stew', stack: 40, perish: 10 * D, food: { health: 12, hunger: 150, sanity: 5, type: 'meat' }, hogTreat: true },
  { id: 'kabobs', name: 'Kabobs', stack: 40, perish: 15 * D, food: { health: 3, hunger: 37.5, sanity: 5, type: 'meat', temp: 40, tempTime: 15 }, hogTreat: true },
  { id: 'ratatouille', name: 'Ratatouille', stack: 40, perish: 15 * D, food: { health: 3, hunger: 25, sanity: 5, type: 'veggie' } },
  { id: 'berryjam', name: 'Bramble Jam', stack: 40, perish: 15 * D, food: { health: 3, hunger: 37.5, sanity: 5, type: 'veggie' } },
  { id: 'fruitmedley', name: 'Fruit Medley', stack: 40, perish: 6 * D, food: { health: 20, hunger: 25, sanity: 5, type: 'veggie', temp: -30, tempTime: 5 } },
  { id: 'frogbun', name: 'Frog Leg Bun', stack: 40, perish: 15 * D, food: { health: 20, hunger: 37.5, sanity: 5, type: 'meat' }, hogTreat: true },
  { id: 'stuffedeggplant', name: 'Stuffed Eggplant', stack: 40, perish: 15 * D, food: { health: 3, hunger: 37.5, sanity: 5, type: 'veggie', temp: 40, tempTime: 5 } },
  { id: 'pumpkinstew', name: 'Harvest Stew', stack: 40, perish: 10 * D, food: { health: 20, hunger: 62.5, sanity: 10, type: 'veggie', temp: 40, tempTime: 10 } },
  { id: 'monsterlasagna', name: 'Monster Lasagna', stack: 40, perish: 6 * D, food: { health: -20, hunger: 37.5, sanity: -20, type: 'monster' } },
  { id: 'wetgoop', name: 'Wet Goop', stack: 40, perish: 6 * D, food: { health: 0, hunger: 0, sanity: 0, type: 'generic' } },
];

const tools: ItemDef[] = [
  { id: 'axe', name: 'Axe', stack: 1, tool: { chop: 1 }, uses: 100, weapon: { damage: 27.2 }, desc: 'Chop chop.' },
  { id: 'pickaxe', name: 'Pickaxe', stack: 1, tool: { mine: 1 }, uses: 33, weapon: { damage: 27.2 }, desc: 'For breaking rocks, not hearts.' },
  { id: 'shovel', name: 'Shovel', stack: 1, tool: { dig: 1 }, uses: 25, weapon: { damage: 17 }, desc: 'Dig it up, move it somewhere nicer.' },
  { id: 'hammer', name: 'Hammer', stack: 1, tool: { hammer: 1 }, uses: 75, weapon: { damage: 17 }, desc: 'Un-building is still building.' },
  { id: 'razor', name: 'Razor', stack: 1, tags: ['razor'], desc: 'For shearing sleepy beasts.' },
  { id: 'torch', name: 'Torch', stack: 1, time: T.TORCH_TIME, equip: { slot: 'hand', light: T.TORCH_RADIUS, heat: 15 }, weapon: { damage: 17 }, tags: ['lighter'], desc: 'A little piece of day.' },
  { id: 'umbrella', name: 'Umbrella', stack: 1, time: 6 * D, equip: { slot: 'hand', waterproof: 0.9, summer: 120 }, weapon: { damage: 10 }, desc: 'The sky is falling. On purpose.' },
  { id: 'spear', name: 'Spear', stack: 1, uses: 150, weapon: { damage: 34 }, desc: 'Pointy end goes toward the monster.' },
  { id: 'logsuit', name: 'Log Armor', stack: 1, armor: { absorb: 0.8, hp: 315 }, equip: { slot: 'body' }, fuel: 360, desc: 'Wearing a tree. Fashionable.' },
  { id: 'hoghelm', name: 'Hog-hide Helm', stack: 1, armor: { absorb: 0.8, hp: 450 }, equip: { slot: 'head' }, desc: 'Keeps my thoughts inside my skull.' },
  { id: 'strawhat', name: 'Straw Hat', stack: 1, time: 5 * D, equip: { slot: 'head', summer: 60, waterproof: 0.2 }, desc: 'Shade you can wear.' },
  { id: 'garland', name: 'Flower Garland', stack: 1, perish: 6 * D, equip: { slot: 'head', sanity: 1.33 }, desc: 'Pretty things help.' },
  { id: 'woolcap', name: 'Wool Cap', stack: 1, time: 10 * D, equip: { slot: 'head', insulation: 120, sanity: 1.33 }, desc: 'Warm ears, warm heart.' },
  { id: 'earmuffs', name: 'Rabbit Earmuffs', stack: 1, time: 5 * D, equip: { slot: 'head', insulation: 60 }, desc: 'Sorry, rabbits.' },
  { id: 'tophat', name: 'Top Hat', stack: 1, time: 8 * D, equip: { slot: 'head', sanity: 3.33, waterproof: 0.2 }, desc: 'Dignity, restored.' },
  { id: 'shagcoat', name: 'Shag Coat', stack: 1, time: 10 * D, equip: { slot: 'body', insulation: 240, waterproof: 0.2 }, desc: 'I look like a beast. I feel warm.' },
  { id: 'backpack', name: 'Backpack', stack: 1, equip: { slot: 'body' }, tags: ['backpack'], desc: 'More pockets, more problems solved.' },
  { id: 'thermalstone', name: 'Thermal Stone', stack: 1, tags: ['heatrock'], desc: 'Holds warmth. Or cold. It is patient.' },
  { id: 'salve', name: 'Healing Salve', stack: 40, heal: 20, desc: 'Stings in a healing way.' },
  { id: 'strawroll', name: 'Straw Roll', stack: 10, fuel: 360, tags: ['bedroll'], desc: 'Sleep through the dark. Mostly.' },
  { id: 'trap_item', name: 'Trap', stack: 10, deploy: 'trap', desc: 'For small, unlucky things.' },
  { id: 'wall_wood_item', name: 'Wood Wall', stack: 20, fuel: 30, deploy: 'wall_wood', desc: 'A line in the dirt.' },
  { id: 'wall_stone_item', name: 'Stone Wall', stack: 20, deploy: 'wall_stone', desc: 'A line in the dirt, but serious.' },
];

defineItems([...resources, ...foods, ...tools]);
