import { definePrefabs, type PrefabDef } from './defs';
import { T } from './tuning';

const mob = (
  hp: number,
  damage: number,
  period: number,
  range: number,
  walk: number,
  run: number,
): Pick<PrefabDef, 'components'>['components'] => ({
  health: { cur: hp, max: hp },
  combat: { damage, period, range, cooldownUntil: 0 },
  locomotor: { walk, run, vx: 0, vy: 0, dest: null },
});

const flora: PrefabDef[] = [
  {
    id: 'pine_tree',
    name: 'Pine Tree',
    tags: ['tree', 'plant'],
    radius: 0.6,
    size: 5,
    work: { action: 'chop', amount: 10 },
    components: { growable: { stage: 1 } },
    burnable: { time: T.BURN_TIME_TREE, becomes: 'burnt_tree' },
    examine: 'Tall, quiet, and full of logs.',
    mapColor: '#2f4a2c',
  },
  {
    id: 'pine_stump',
    name: 'Stump',
    tags: ['stump'],
    size: 1,
    work: { action: 'dig', amount: 1 },
    workLoot: [{ item: 'log' }],
    burnable: { time: T.BURN_TIME_SMALL },
    examine: 'It had a good run.',
  },
  {
    id: 'pine_sapling',
    name: 'Pine Sapling',
    tags: ['plant'],
    size: 1,
    work: { action: 'dig', amount: 1 },
    burnable: { time: T.BURN_TIME_SMALL },
    examine: 'Grow, little one. Grow and be chopped.',
  },
  {
    id: 'burnt_tree',
    name: 'Burnt Tree',
    tags: ['tree'],
    radius: 0.4,
    size: 4,
    work: { action: 'chop', amount: 1 },
    workLoot: [{ item: 'charcoal' }],
    examine: 'Crispy.',
    mapColor: '#2a2522',
  },
  {
    id: 'grass',
    name: 'Grass Tuft',
    tags: ['plant', 'pickable'],
    size: 1.4,
    pick: { item: 'cutgrass', n: 1, regrow: T.GRASS_REGROW },
    burnable: { time: T.BURN_TIME_SMALL, loot: [{ item: 'ash' }] },
    examine: 'Tall grass. Useful grass.',
  },
  {
    id: 'sapling',
    name: 'Sapling',
    tags: ['plant', 'pickable'],
    size: 1.6,
    pick: { item: 'twigs', n: 1, regrow: T.SAPLING_REGROW },
    burnable: { time: T.BURN_TIME_SMALL, loot: [{ item: 'ash' }] },
    examine: 'It wants to be a tree when it grows up.',
  },
  {
    id: 'berrybush',
    name: 'Berry Bush',
    tags: ['plant', 'pickable'],
    size: 1.8,
    radius: 0.3,
    pick: { item: 'berries', n: 1, regrow: T.BERRY_REGROW },
    burnable: { time: T.BURN_TIME_SMALL, loot: [{ item: 'ash' }] },
    examine: 'Berries! Nature’s candy.',
    mapColor: '#7a3b4a',
  },
  {
    id: 'carrot_plant',
    name: 'Carrot',
    tags: ['plant', 'pickable'],
    size: 0.8,
    pick: { item: 'carrot', n: 1, regrow: 0, remove: true },
    examine: 'A carrot, sticking out of the ground.',
  },
  {
    id: 'flower',
    name: 'Flower',
    tags: ['plant', 'pickable', 'flower'],
    size: 0.8,
    pick: { item: 'petals', n: 1, regrow: 0, remove: true, sanity: T.SANITY_PICK_FLOWER },
    sanityAura: 1.5,
    burnable: { time: 3 },
    examine: 'A small, bright defiance.',
  },
  {
    id: 'reeds',
    name: 'Reeds',
    tags: ['plant', 'pickable'],
    size: 1.6,
    pick: { item: 'cutreeds', n: 1, regrow: T.REEDS_REGROW },
    burnable: { time: T.BURN_TIME_SMALL },
    examine: 'They whisper when the wind blows.',
  },
];

const minerals: PrefabDef[] = [
  {
    id: 'boulder',
    name: 'Boulder',
    tags: ['rock'],
    radius: 0.9,
    size: 2,
    work: { action: 'mine', amount: 6 },
    workLoot: [
      { item: 'rocks', n: 2 },
      { item: 'rocks', chance: 0.6 },
      { item: 'flint', n: 1 },
      { item: 'flint', chance: 0.6 },
    ],
    examine: 'A big rock. Rocks are good.',
    mapColor: '#6b6a66',
  },
  {
    id: 'boulder_gold',
    name: 'Veined Boulder',
    tags: ['rock'],
    radius: 0.9,
    size: 2,
    work: { action: 'mine', amount: 6 },
    workLoot: [
      { item: 'rocks', n: 2 },
      { item: 'gold', n: 1 },
      { item: 'gold', chance: 0.35 },
      { item: 'flint', chance: 0.5 },
    ],
    examine: 'Something glitters in there.',
    mapColor: '#8f7d45',
  },
];

const structures: PrefabDef[] = [
  {
    id: 'campfire',
    name: 'Campfire',
    tags: ['fire', 'structure', 'cookfire'],
    size: 1.4,
    components: { fueled: { fuel: T.CAMPFIRE_START } },
    structure: true,
    examine: 'Warm. Bright. Mine.',
    mapColor: '#e08a2c',
  },
  {
    id: 'firepit',
    name: 'Fire Pit',
    tags: ['fire', 'structure', 'cookfire'],
    radius: 0.8,
    size: 1.4,
    components: { fueled: { fuel: T.FIREPIT_START } },
    structure: true,
    hammerLoot: [{ item: 'rocks', n: 6 }, { item: 'log' }],
    examine: 'Contained. Reliable. Beautiful.',
    mapColor: '#e08a2c',
  },
  {
    id: 'tinkers_bench',
    name: "Tinker's Bench",
    tags: ['structure', 'prototyper'],
    radius: 1,
    size: 3,
    structure: true,
    burnable: { time: 10, loot: [{ item: 'ash' }] },
    hammerLoot: [{ item: 'log', n: 2 }, { item: 'rocks', n: 2 }],
    examine: 'Whirring gears and good ideas.',
    mapColor: '#b38b4d',
  },
  {
    id: 'alembic',
    name: 'Alembic Engine',
    tags: ['structure', 'prototyper'],
    radius: 1.1,
    size: 3.4,
    structure: true,
    hammerLoot: [{ item: 'boards', n: 2 }, { item: 'cutstone' }, { item: 'gold', n: 3 }],
    examine: 'It bubbles with forbidden chemistry.',
    mapColor: '#6b8fb3',
  },
  {
    id: 'cookpot',
    name: 'Cook Pot',
    tags: ['structure'],
    radius: 0.8,
    size: 2.2,
    container: 4,
    components: { cooker: {} },
    structure: true,
    hammerLoot: [{ item: 'cutstone', n: 2 }, { item: 'charcoal', n: 3 }],
    light: { radius: 2.4, intensity: 0.6, color: '#ffae5a' },
    examine: 'Four ingredients in, something delicious out. Hopefully.',
    mapColor: '#8a5a3a',
  },
  {
    id: 'chest',
    name: 'Chest',
    tags: ['structure'],
    radius: 0.7,
    size: 1.6,
    container: 9,
    structure: true,
    burnable: { time: 10, loot: [{ item: 'ash' }] },
    hammerLoot: [{ item: 'boards', n: 2 }],
    examine: 'Keeps my things safe from... things.',
    mapColor: '#9a6b3c',
  },
  {
    id: 'icebox',
    name: 'Ice Box',
    tags: ['structure', 'fridge'],
    radius: 0.7,
    size: 2,
    container: 9,
    structure: true,
    hammerLoot: [{ item: 'gold' }, { item: 'boards', n: 2 }],
    examine: 'Cold inside, somehow. I don’t ask.',
    mapColor: '#a9c6d6',
  },
  {
    id: 'drying_rack',
    name: 'Drying Rack',
    tags: ['structure'],
    size: 2.4,
    components: { dryer: {} },
    structure: true,
    burnable: { time: 8, loot: [{ item: 'ash' }] },
    hammerLoot: [{ item: 'twigs', n: 2 }, { item: 'rope' }],
    examine: 'Sun, wind, and patience make jerky.',
  },
  {
    id: 'farm_plot',
    name: 'Garden Plot',
    tags: ['structure'],
    size: 1.2,
    components: { farm: {} },
    structure: true,
    hammerLoot: [{ item: 'log', n: 2 }, { item: 'cutgrass', n: 4 }],
    examine: 'Plant a seed. Wait. Eat.',
    mapColor: '#5c4a2e',
  },
  {
    id: 'wall_wood',
    name: 'Wood Wall',
    tags: ['structure', 'wall'],
    radius: 0.55,
    size: 2,
    components: { health: { cur: 200, max: 200 } },
    structure: true,
    burnable: { time: 10 },
    hammerLoot: [{ item: 'boards', chance: 0.5 }],
    examine: 'Keep out. Or in.',
    mapColor: '#8a6a44',
  },
  {
    id: 'wall_stone',
    name: 'Stone Wall',
    tags: ['structure', 'wall'],
    radius: 0.55,
    size: 2,
    components: { health: { cur: 400, max: 400 } },
    structure: true,
    hammerLoot: [{ item: 'cutstone', chance: 0.5 }],
    examine: 'Solid. Stubborn. Like me.',
    mapColor: '#8d8d88',
  },
  {
    id: 'hog_house',
    name: 'Hog House',
    tags: ['structure', 'home'],
    radius: 1.1,
    size: 4,
    components: { spawner: { children: [], stock: 1 } },
    structure: true,
    burnable: { time: 15, loot: [{ item: 'ash' }] },
    hammerLoot: [{ item: 'boards', n: 2 }, { item: 'cutstone' }, { item: 'hogskin', n: 2 }],
    examine: 'Someone lives here. Someone with a snout.',
    mapColor: '#a07046',
  },
  {
    id: 'tent',
    name: 'Tent',
    tags: ['structure', 'bed'],
    radius: 1,
    size: 3,
    structure: true,
    burnable: { time: 10, loot: [{ item: 'ash' }] },
    hammerLoot: [{ item: 'silk', n: 3 }, { item: 'twigs', n: 2 }],
    examine: 'A room of my own.',
    mapColor: '#b9a27c',
  },
  {
    id: 'trap',
    name: 'Trap',
    tags: ['trap'],
    size: 1,
    components: { trap: { set: true } },
    examine: 'Something small will wander in.',
  },
];

const dens: PrefabDef[] = [
  {
    id: 'rabbit_hole',
    name: 'Rabbit Hole',
    tags: ['home'],
    size: 1,
    components: { spawner: { children: [], stock: 1 } },
    work: { action: 'dig', amount: 1 },
    examine: 'Something fluffy lives down there.',
  },
  {
    id: 'spider_den',
    name: 'Spider Den',
    tags: ['home', 'hostile_home'],
    radius: 1.2,
    size: 3.6,
    components: { spawner: { children: [], stock: 2 }, growable: { stage: 0 }, health: { cur: 250, max: 250 } },
    sanityAura: -8,
    loot: [{ item: 'silk', n: 2 }, { item: 'silk', chance: 0.5 }, { item: 'monstermeat' }],
    burnable: { time: 12, loot: [{ item: 'silk' }] },
    examine: 'That’s a lot of legs in one place.',
    mapColor: '#d7d4cc',
  },
  {
    id: 'pond',
    name: 'Pond',
    tags: ['pond', 'home'],
    radius: 2.4,
    size: 2,
    components: { spawner: { children: [], stock: 2 } },
    examine: 'Murky. Something croaks.',
    mapColor: '#3a5a6a',
  },
  {
    id: 'gravestone',
    name: 'Headstone',
    tags: ['grave'],
    radius: 0.5,
    size: 2,
    sanityAura: -2,
    examine: 'The name has worn away.',
    mapColor: '#7a7a82',
  },
  {
    id: 'grave_mound',
    name: 'Grave',
    tags: ['grave'],
    size: 1,
    work: { action: 'dig', amount: 1 },
    workLoot: [
      { item: 'gold', chance: 0.4 },
      { item: 'nightmarefuel', chance: 0.3 },
      { item: 'flint', chance: 0.4 },
      { item: 'tophat', chance: 0.05 },
    ],
    examine: 'I shouldn’t. ...Should I?',
  },
  {
    id: 'hollow_obelisk',
    name: 'Lamp Post',
    tags: ['landmark'],
    radius: 0.5,
    size: 4,
    light: { radius: 7, intensity: 0.9, color: '#ffd28a' },
    examine: 'A lamp. Here? It still burns.',
    mapColor: '#ffd28a',
  },
];

const mobs: PrefabDef[] = [
  {
    id: 'player',
    name: 'Silas',
    tags: ['player', 'character'],
    radius: 0.5,
    size: 3,
    components: {
      health: { cur: T.PLAYER_HEALTH, max: T.PLAYER_HEALTH },
      hunger: { cur: T.PLAYER_HUNGER, max: T.PLAYER_HUNGER },
      sanity: { cur: T.PLAYER_SANITY, max: T.PLAYER_SANITY },
      temperature: { cur: T.TEMP_START },
      wetness: { cur: 0 },
      locomotor: { walk: T.PLAYER_WALK, run: T.PLAYER_WALK, vx: 0, vy: 0, dest: null },
      combat: { damage: T.PLAYER_DAMAGE, period: T.PLAYER_ATTACK_PERIOD, range: T.PLAYER_ATTACK_RANGE, cooldownUntil: 0 },
    },
  },
  {
    id: 'rabbit',
    name: 'Rabbit',
    tags: ['animal', 'prey', 'small'],
    size: 1.2,
    components: { health: { cur: 25, max: 25 }, locomotor: { walk: 2, run: 5, vx: 0, vy: 0, dest: null } },
    loot: [{ item: 'morsel' }],
    brain: 'rabbit',
    examine: 'Twitchy little meal.',
  },
  {
    id: 'crow',
    name: 'Crow',
    tags: ['animal', 'bird', 'small'],
    size: 1,
    components: { health: { cur: 25, max: 25 }, locomotor: { walk: 1.5, run: 8, vx: 0, vy: 0, dest: null } },
    loot: [{ item: 'morsel' }],
    brain: 'bird',
    examine: 'It’s watching me. Judging.',
  },
  {
    id: 'hog',
    name: 'Hogfolk',
    tags: ['hog', 'character', 'tradeable'],
    radius: 0.5,
    size: 3.2,
    components: mob(250, 33, 3, 2.2, 3, 5),
    loot: [{ item: 'meat', chance: 0.75 }, { item: 'hogskin', chance: 0.25 }],
    brain: 'hog',
    sanityAura: 0,
    examine: 'A stout fellow with a suspicious snout.',
  },
  {
    id: 'shagbeast',
    name: 'Shagbeast',
    tags: ['animal', 'beast', 'herd', 'large'],
    radius: 1.1,
    size: 4,
    components: mob(1000, 34, 4, 3, 1.5, 7),
    loot: [{ item: 'meat', n: 4 }, { item: 'wool', n: 3 }],
    brain: 'shagbeast',
    examine: 'Enormous, woolly, and mostly calm.',
  },
  {
    id: 'spider',
    name: 'Spider',
    tags: ['monster', 'spider', 'hostile'],
    radius: 0.5,
    size: 1.8,
    hostile: true,
    components: mob(100, 20, 3, 2.2, 3, 5),
    loot: [{ item: 'monstermeat', chance: 0.5 }, { item: 'silk', chance: 0.25 }, { item: 'spidergland', chance: 0.25 }],
    sanityAura: -25,
    brain: 'spider',
    examine: 'Too many legs. Far too many eyes.',
  },
  {
    id: 'spider_warrior',
    name: 'Spider Warrior',
    tags: ['monster', 'spider', 'hostile'],
    radius: 0.55,
    size: 2.2,
    hostile: true,
    components: mob(400, 20, 4, 2.6, 4, 5),
    loot: [{ item: 'monstermeat', chance: 0.5 }, { item: 'silk', chance: 0.25 }, { item: 'spidergland', chance: 0.25 }],
    sanityAura: -40,
    brain: 'spider',
    examine: 'This one looks like it means it.',
  },
  {
    id: 'frog',
    name: 'Frog',
    tags: ['animal', 'frog', 'hostile'],
    radius: 0.4,
    size: 1.3,
    hostile: true,
    components: mob(100, 10, 1, 1.8, 4, 8),
    loot: [{ item: 'froglegs' }],
    brain: 'frog',
    examine: 'Grumpy and damp.',
  },
  {
    id: 'hound',
    name: 'Hollow Hound',
    tags: ['monster', 'hound', 'hostile'],
    radius: 0.55,
    size: 2.2,
    hostile: true,
    components: mob(150, 20, 2, 2.4, 10, 10),
    loot: [{ item: 'monstermeat' }, { item: 'houndstooth', chance: 0.125 }],
    sanityAura: -40,
    brain: 'hound',
    examine: 'All teeth, no manners.',
  },
  {
    id: 'crawling_dread',
    name: 'Crawling Dread',
    tags: ['shadow', 'hostile', 'monster'],
    radius: 0.6,
    size: 2.6,
    hostile: true,
    components: { ...mob(300, 20, 2.5, 2.4, 3, 3), shadow: true },
    loot: [{ item: 'nightmarefuel' }, { item: 'nightmarefuel', chance: 0.5 }],
    sanityAura: -100,
    brain: 'shadow',
    examine: 'It isn’t there. It isn’t there. It’s there.',
  },
  {
    id: 'dread_beak',
    name: 'Dread Beak',
    tags: ['shadow', 'hostile', 'monster'],
    radius: 0.6,
    size: 3.4,
    hostile: true,
    components: { ...mob(400, 50, 1.5, 2.6, 7, 7), shadow: true },
    loot: [{ item: 'nightmarefuel' }, { item: 'nightmarefuel', chance: 0.5 }],
    sanityAura: -100,
    brain: 'shadow',
    examine: 'A beak made of bad thoughts.',
  },
];

const misc: PrefabDef[] = [
  { id: 'item', name: 'Item', size: 0.9 },
  {
    id: 'sign_start',
    name: 'Strange Portal',
    tags: ['landmark'],
    radius: 1,
    size: 3.5,
    light: { radius: 3, intensity: 0.35, color: '#a58cff' },
    examine: 'That’s how I got here. It won’t let me back.',
    mapColor: '#a58cff',
  },
];

definePrefabs([...flora, ...minerals, ...structures, ...dens, ...mobs, ...misc]);
